ToDo_List/ToDo_List/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 3rd party app path
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    # local app path
    path('', include('todo.urls')),
]

ToDo_List/todo/urls.py
from django.urls import path
from . import views

app_name='todo'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('delete/<int:id>/', views.Item_Delete, name='item-delete'),
    path('cross_off/<int:id>/', views.cross_off, name='item-cross-off'),
    path('uncross/<int:id>/', views.uncross, name='item-uncross'),
    path('edit/<int:id>/', views.edit_view, name='item-edit'),
]

ToDo_List/todo/models.py
from django.db import models

# Create your models here.

class ToDo_List(models.Model):
    item=models.CharField(
        max_length=250,
        verbose_name='To-Do List',
        unique=True,
    )
    complated=models.BooleanField(
        default=False
    )
    def __str__(self):
        return self.item + ' | ' + str(self.complated)
    class Meta:
        verbose_name = 'To-Do List'
        verbose_name_plural = 'To-Do Lists'
    

ToDo_List/todo/forms.py
from django import forms

from .models import ToDo_List

class ToDo_List_Form(forms.ModelForm):
    item=forms.CharField(
        max_length=250, 
        required=False,
        label='',
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control mr-sm-2',
                'placeholder' : 'Add Item',
            }
        )    
    )
    class Meta:
        model=ToDo_List
        fields=[
            'item',
            'complated',
        ]

ToDo_List/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .models import ToDo_List
from .forms import ToDo_List_Form


# Create your views here.

def homepage(request):
    if request.POST:
        form=ToDo_List_Form(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                ('Item Has Been Added To List!')
            )
            object_list = ToDo_List.objects.all()
            return render(
                request=request,
                template_name='todo/home-page.html',
                context={
                    'object_list' : object_list
                }
            )
    else:
        object_list = ToDo_List.objects.all()
        return render(
            request=request,
            template_name='todo/home-page.html',
            context={
                'object_list' : object_list
            }
        )


def Item_Delete(request, id):
    obj=get_object_or_404(ToDo_List, id=id)
    if obj:
        obj.delete()
    messages.success(
        request,
        ('It Has Been Deleted!')
    )
    return redirect('todo:home')


def cross_off(request, id):
    obj=get_object_or_404(ToDo_List, id=id)
    if obj:
        obj.complated=True
        obj.save()
    # messages.success(
    #     request,
    #     ('It Has Been Deleted!')
    # )
    return redirect('todo:home')

def uncross(request, id):
    obj=get_object_or_404(ToDo_List, id=id)
    if obj:
        obj.complated=False
        obj.save()
    # messages.success(
    #     request,
    #     ('It Has Been Deleted!')
    # )
    return redirect('todo:home')


def edit_view(request, id):
    if request.method == 'POST':
        obj=get_object_or_404(ToDo_List, id=id)
        form=ToDo_List_Form(request.POST or None, instance=obj)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                ('Item Has Been Edited!')
            )
            return redirect('todo:home')
            # object_list = ToDo_List.objects.all()
            # return render(
            #     request=request,
            #     template_name='todo/home-page.html',
            #     context={
            #         'object_list' : object_list
            #     }
            # )
    else:
        obj=get_object_or_404(ToDo_List, id=id)
        return render(
            request=request,
            template_name='todo/edit-page.html',
            context={
                'object' : obj
            }
        )

ToDo_List/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>

    <!-- Compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="{% static 'todo/css/MaterializeCss.css' %}"> -->
    <!-- Compiled and minified JavaScript -->
    <!-- <script src="{% static 'todo/js/MaterializeJs.js' %}"></script> -->
    <!-- <script src="{% static 'todo/js/MaterializeDropdawnList.js' %}"></script> -->
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/home.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'todo/css/materialize.css' %}"> -->


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/BootstarpCss.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/home.css' %}">

</head>

<body>
    {% include "todo/includes/navbar.html" %} {% include "todo/includes/messages.html" %}
    <div class='container'>
        {% block content %} {% endblock %}
    </div>
</body>
<script>
    M.AutoInit();
</script>

</html>

ToDo_List/templates/todo/edit-page.html
{% extends "todo/base.html" %} {% block content %} {% if object %}
<form action="." class="form-inline my-2 my-lg-0" method="POST">
    {% csrf_token %}
    <input type="search" placeholder="{{ object.item }}" value="{{ object.item }}" name="item" aria-label="Search" class="form-control mr-sm-2">
    <input type="hidden" name="complated" value="{{ object.complated }}">
    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Edit Item</button>
</form>
{% endif %} {% endblock %}

ToDo_List/templates/todo/home-page.html
{% extends "todo/base.html" %}
<br> {% block content %} {% if object_list %}
<table class="table table-bordered">
    {% for object in object_list %} {% if object.complated %}
    <tr class="table-secondary">
        <td class="striker"><a href="{% url 'todo:item-edit' object.id %}">{{ object.item }}</a></td>
        <td>
            <center>
                <a href="{% url 'todo:item-uncross' object.id %}">Uncross</a>
            </center>
        </td>
        <td>
            <a href="{% url 'todo:item-delete' object.id %}">
                <center>Delete</center>
            </a>
        </td>
    </tr>
    {% else %}
    <tr>
        <td><a href="{% url 'todo:item-edit' object.id %}">{{ object.item }}</a></td>
        <td>
            <center>
                <a href="{% url 'todo:item-cross-off' object.id %}">Cross-Off</a>
            </center>
        </td>
        <td>
            <a href="{% url 'todo:item-delete' object.id %}">
                <center>Delete</center>
            </a>
        </td>
    </tr>
    {% endif %} {% endfor %}</table> {% endif %} {% endblock %}

ToDo_List/templates/todo/includes/messages.html
{% if messages %} {% for message in messages %} {% if message.tags == 'success' %}
<script>
    M.toast({
        html: "{{ message }}",
        classes: "blue rounded",
        displayLength: 2000
    })
</script>
{% elif message.tags == 'info' %}
<script>
    M.toast({
        html: "{{ message }}",
        classes: "green rounded",
        displayLength: 2000
    })
</script>
{% elif message.tags == 'warning' %}
<script>
    M.toast({
        html: "{{ message }}",
        classes: "orange rounded",
        displayLength: 10000
    })
</script>
{% elif message.tags == 'error' %}
<script>
    M.toast({
        html: "{{ message }}",
        classes: "red rounded",
        displayLength: 10000
    })
</script>
{% endif %} {% endfor %} {% endif %}

ToDo_List/templates/todo/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="{% url 'todo:home' %}" class="navbar-brand">TODO LIST</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a href="/account">{{ user.username|title }}</a></li>
            <li><a href="/logout">Logout</a></li>
            {% else %}
            <li><a href="/register">Register</a></li>
            <li><a href="/login">Login</a></li>
            {% endif %}
            <li><a href="/news">News</a></li>
        </ul> -->
        <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Add Item" aria-label="Search" name="item">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add To List</button>
        </form>
    </div>
</nav>